name: Practicum
channels:
  - conda-forge
dependencies:
  - python=3.10
  - black
  - flake8
  - isort
  - pip
  - typer
  - loguru
  - tqdm
  - ipython
  - jupyterlab
  - matplotlib
  - notebook
  - numpy
  - pandas
  - polars
  - pyarrow
  - seaborn
  - scipy
  - scikit-learn
  - pip:
    - group-lasso
    - python-dotenv
    - mkdocs
    - -e .